# docker compose build worker

FROM node:20-slim AS base

# Install pnpm
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable

# Install system packages
RUN apt update && \
  apt install -y \
  curl \
  git \
  vim \
  jq \
  netcat-openbsd \
  apt-transport-https \
  ca-certificates \
  gnupg \
  lsb-release \
  wget \
  gpg \
  xvfb \
  gh \
  && rm -rf /var/lib/apt/lists/*

# Install Docker cli
RUN curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg \
  && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null \
  && apt update && apt install -y docker-ce-cli \
  && rm -rf /var/lib/apt/lists/*

# Install VS Code
RUN wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > packages.microsoft.gpg \
  && install -D -o root -g root -m 644 packages.microsoft.gpg /etc/apt/keyrings/packages.microsoft.gpg \
  && echo "deb [arch=amd64,arm64,armhf signed-by=/etc/apt/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main" | tee /etc/apt/sources.list.d/vscode.list > /dev/null \
  && rm -f packages.microsoft.gpg \
  && apt update && apt install -y code \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /roo

# Install extensions
RUN mkdir -p /roo/.vscode \
  && code --no-sandbox --user-data-dir /roo/.vscode --install-extension dbaeumer.vscode-eslint \
  && code --no-sandbox --user-data-dir /roo/.vscode --install-extension esbenp.prettier-vscode \
  && code --no-sandbox --user-data-dir /roo/.vscode --install-extension csstools.postcss \
  && code --no-sandbox --user-data-dir /roo/.vscode --install-extension RooVeterinaryInc.roo-cline

# Clone repo
ARG GH_TOKEN
ENV GH_TOKEN=$GH_TOKEN
RUN gh repo clone RooCodeInc/Roo-Code

WORKDIR /roo/Roo-Code
RUN pnpm install

WORKDIR /roo
CMD ["bash"]
